### ISSUE TITLE
Edit feed viewing

### ISSUE THREAD

**Issue by theoria-dev** [periakteon/pate-finder#33]
Authenticated user ile authenticated olmayan kullanıcıların feed'leri farklı olacak. Giriş yapmamış kullanıcılar son postları ve en çok beğenilen postları random bir şekilde görsün. Belki bunun için sayfanın en yukarısına "Son Postlar" ve "En Çok Beğenilenler" diye iki ayrı opsiyon koyabiliriz (Twitter'dakine benzer).

@periakteon

**Comment by periakteon** [comment]
abort
